apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  host: "postgres"
  name: "backendservice"
  postgresql.conf: |
    shared_buffers = 64MB
    work_mem = 4MB
    maintenance_work_mem = 16MB