spring:
  application:
    name: notification-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  profiles:
    active: monitor
  rabbitmq:
    host: localhost  #rabbitmq.default.svc.cluster.local
    port: 5672
    username: guest #user
    password: guest #password
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
server:
  port: 8086

