# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: post-deployment
deploymentLabel: post
appName: post-service
serviceName: post-service
replicaCount: 3

image:
  repository: egokirill/post-service
  tag: latest
  imagePullPolicy: Always

#containerPort: 8080

service:
  type: ClusterIP
  port: 8084
  targetPort: 8084

config_enabled: true
postgresql_enabled: true
sendgrid_enabled: true
aws_enabled: true