spring:
  application:
    name: post-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  profiles:
    active: monitor,general
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  flyway:
    enabled: true
    url: jdbc:postgresql://microservices-db.cvgyimgky69h.eu-north-1.rds.amazonaws.com:5432/post-service?serverTimezone=UTC&createDatabaseIfNotExist=true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: postgres
    password: 7L6aX8jfG4
    baseline-version: 0


s3:
  endpointUrl: https://s3.eu-north-1.amazonaws.com #https://s3.amazonaws.com
  accessKeyId: AKIAXFASNBMFJDAN6DEW  #AKIAXFASNBMFIHPPHW53
  secretKey: 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  #plTYxqRHcLGIvN0eX+iQQUGLq/eGwJCXdTxeWv2j
  bucketName: benedigto-bucket
  region: eu-north-1





