spring:
  application:
    name: post-service
  config:
    import: configserver:http://localhost:8888

  security:
    basic:
      enabled: false
    ignored: /**
    oauth2:
      client:
        registration:
          keycloak:
            provider: my-provider
            client-id: x
            client-secret: XHeGWMOt2eXMkCvMAbI0rxCzj5xbuHMD
            authorization-grant-type: authorization_code
        provider:
          my-provider:
            issuer-uri: http://localhost:8080/realms/master
            jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  auth:
    converter:
      resource-id: x