# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: config-deployment
deploymentLabel: config
appName: config-service
serviceName: config-service
replicaCount: 1

image:
  repository: egokirill/config-service
  tag: latest
  imagePullPolicy: Always

#containerPort: 8080

service:
  type: ClusterIP
  port: 8888
  targetPort: 8888

config_enabled: false
postgresql_enabled: false
aws_enabled: false