
deploymentName: config-deployment
deploymentLabel: config
appName: config-service
serviceName: config-service
replicaCount: 3

image:
  repository: egokirill/config-service
  tag: latest
  imagePullPolicy: Always


service:
  type: ClusterIP
  port: 8888
  targetPort: 8888

git_env: true
config_enabled: false
postgresql_enabled: false
aws_enabled: false