spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default:
        filters:
          TokenRelay=
      routes:
        - id: notif
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
        - id: profiles
          uri: lb://profile-service
          predicates:
            - Path=/profiles/**
          filters:
            - name: CircuitBreaker
              args:
                name: ClientCircuitBreaker
                fallbackUri: forward:/fallback/profiles
        - id: post
          uri: lb://post-service
          predicates:
            - Path=/posts/**
          filters:
            - name: CircuitBreaker
              args:
                name: ClientCircuitBreaker
                fallbackUri: forward:/fallback/posts
