spring:
  application:
    name: gateway-service
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/test/protocol/openid-connect/certs
        #issuer-uri: http://localhost:8080/auth/realms/spring-boot-microservices-realm


  config:
    import: configserver:http://localhost:8888
  profiles:
    active: rout

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  auth:
    converter:
      resource-id: x


server:
  port: 8765

resilience4j:
  circuit-breaker:
    configs:
      default:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50.0
        waitDurationInOpenState: 5s
        slowCallDurationThreshold: 200ms
        slowCallRateThreshold: 50.0
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5




