spring:
  application:
    name: profile-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888} #configserver:http://localhost:8888
  profiles:
    active: monitor,general



