# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: profile-deployment
deploymentLabel: profile-deployment
appName: profile-service
serviceName: profile-service
replicaCount: 1

image:
  repository: egokirill/profile-service
  tag: latest
  imagePullPolicy: IfNotPresent

#containerPort: 8080

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083

config_enabled: true
postgresql_enabled: true