
deploymentName: profile-deployment
deploymentLabel: profile
appName: profile-service
serviceName: profile-service
replicaCount: 3

image:
  repository: egokirill/profile-service
  tag: latest
  imagePullPolicy: Always


service:
  type: ClusterIP
  port: 8083
  targetPort: 8083

config_enabled: true
postgresql_enabled: true
sendgrid_enabled: true
aws_enabled: false