# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gateway-deployment
deploymentLabel: gateway-deployment
appName: gateway-service
serviceName: gateway-server
replicaCount: 1

image:
  repository: egokirill/gateway-service
  tag: latest
  imagePullPolicy: IfNotPresent

#containerPort: 8080

service:
  type: LoadBalancer
  port: 8765
  targetPort: 8765

config_enabled: true
postgresql_enabled: false