
deploymentName: gateway-deployment
deploymentLabel: gateway
appName: gateway-service
serviceName: gateway-service
replicaCount: 3

image:
  repository: egokirill/gateway-service
  tag: latest
  imagePullPolicy: Always

service:
  type: LoadBalancer
  port: 8765
  targetPort: 8765

config_enabled: true
postgresql_enabled: false
aws_enabled: false