# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gateway-deployment
deploymentLabel: gateway
appName: gateway-service
serviceName: gateway-service
replicaCount: 1

image:
  repository: egokirill/gateway-service
  tag: latest
  imagePullPolicy: Always

#containerPort: 8080

service:
  type: LoadBalancer
  port: 8765
  targetPort: 8765

config_enabled: true
postgresql_enabled: false
aws_enabled: false