
{{- define "common.service" -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "msvc-chart.service.name" . }}
spec:
  selector:
    app: {{ include "msvc-chart.deployment.name" . }}
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{.Values.service.targetPort}}
      {{- end }}
