
{{- define "common.service" -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "msvc-chart.service.name" . }}
spec:
  selector:
    app: {{ .Values.deploymentLabel }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- end }}
