# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: notification-deployment
deploymentLabel: notification
appName: notification-service
serviceName: notification-service
replicaCount: 1

image:
  repository: egokirill/notification-service
  tag: latest
  imagePullPolicy: IfNotPresent

#containerPort: 8080

service:
  type: ClusterIP
  port: 8086
  targetPort: 8086

config_enabled: true
postgresql_enabled: false
sendgrid_enabled: true
aws_enabled: false