spring:
  application:
    name: eureka-service
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: monitor
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761