# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Maven projects
        run: |
            mvn -B package -DskipTests=true --file gateway-service/pom.xml
            mvn -B package -DskipTests=true --file eureka-service/pom.xml
            mvn -B package -DskipTests=true --file profile-service/pom.xml
            mvn -B package -DskipTests=true --file post-service/pom.xml
            mvn -B package -DskipTests=true --file config-service/pom.xml
            mvn -B package -DskipTests=true --file planner-entity/pom.xml


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
            docker build -t egokirill/gateway-service:latest ./gateway-service
            docker build -t egokirill/eureka-service:latest ./eureka-service
            docker build -t egokirill/profile-service:latest ./profile-service
            docker build -t egokirill/post-service:latest ./post-service
            docker build -t egokirill/config-service:latest ./config-service
          
            docker push egokirill/gateway-service:latest
            docker push egokirill/eureka-service:latest
            docker push egokirill/profile-service:latest
            docker push egokirill/post-service:latest
            docker push egokirill/config-service:latest

